"""
TELEGBOT Architecture Layer - Event Types and Models

Defines canonical event structures that all layers must use.
"""

from typing import Optional, Dict, Any, Literal
from pydantic import BaseModel
from datetime import datetime


class CanonicalEvent(BaseModel):
    """
    All incoming Telegram updates normalized to this canonical form.
    
    This is the single source of truth for event structure.
    Every event entering the system must be normalized to this form.
    """
    
    # Event identity
    event_id: str  # Unique identifier
    event_type: Literal["message", "callback_query", "join_request", "poll_answer"]
    platform: Literal["telegram"]
    
    # Actor identity
    user_id: Optional[int] = None
    username: Optional[str] = None
    chat_id: int
    
    # Timing
    timestamp: int  # Unix timestamp
    
    # Event content
    text: Optional[str] = None
    callback_data: Optional[str] = None
    
    # Raw Telegram object (preserved)
    raw: Dict[str, Any]
    
    class Config:
        frozen = True  # Immutable


class MessageEvent(CanonicalEvent):
    """Message event - user sends text or media."""
    event_type: Literal["message"] = "message"
    message_id: int
    chat_type: Literal["private", "group", "supergroup", "channel"]


class CallbackQueryEvent(CanonicalEvent):
    """Callback event - user clicks inline button."""
    event_type: Literal["callback_query"] = "callback_query"
    callback_query_id: str
    button_label: Optional[str] = None


class JoinRequestEvent(CanonicalEvent):
    """Join request event - user requests to join group."""
    event_type: Literal["join_request"] = "join_request"
    request_id: str
    full_name: Optional[str] = None


class PollAnswerEvent(CanonicalEvent):
    """Poll answer event - user votes in poll."""
    event_type: Literal["poll_answer"] = "poll_answer"
    poll_id: str
    options: list[int]  # Selected option indices


# Execution intent (generated by Layer 1 - Internal Modules)
class ExecutionIntent(BaseModel):
    """
    Intent generated by Internal Modules.
    
    This is the contract between Layer 1 and Layer 2.
    Layer 1 (Modules) generates intents.
    Layer 2 (Runtime) executes intents.
    """
    
    intent_id: str
    intent_type: Literal[
        "create_draft",
        "preview_post",
        "publish_post",
        "create_ticket",
        "approve_member",
        "broadcast",
    ]
    actor_id: int
    target_type: Literal["post", "ticket", "member", "broadcast"]
    target_id: str
    
    # Intent data
    data: Dict[str, Any]
    
    class Config:
        frozen = True


# Execution plan (generated by Layer 2 - Runtime Services)
class StateMutation(BaseModel):
    """Single state mutation."""
    key: list[str]  # KV key path
    value: Any
    operation: Literal["set", "delete"]


class AuditEntry(BaseModel):
    """Immutable audit log entry."""
    audit_id: str
    timestamp: int
    actor_id: int
    action: str
    resource_type: str
    resource_id: str
    changes: Dict[str, Any]
    success: bool


class OutboxEntry(BaseModel):
    """Staged outbound message."""
    outbox_id: str
    target_chat_id: int
    message_text: str
    buttons: Optional[list[Dict[str, str]]] = None
    created_at: int


class QueueItem(BaseModel):
    """Delivery work item."""
    queue_item_id: str
    outbox_id: str
    retry_count: int = 0
    next_retry_at: int


class ExecutionPlan(BaseModel):
    """
    Immutable execution plan produced by Step 5.
    
    This is the contract between the planning phase and commit phase.
    """
    
    plan_id: str
    timestamp: int
    
    # All mutations to commit atomically
    state_mutations: list[StateMutation]
    audit_entry: AuditEntry
    aggregate_updates: Dict[str, int]  # Counter increments
    outbox_entries: list[OutboxEntry]
    queue_items: list[QueueItem]
    
    class Config:
        frozen = True


# FSM State Definition
class FSMState(BaseModel):
    """Finite State Machine state."""
    state_name: str
    timestamp: int
    data: Dict[str, Any]


# Permission/Security Models
class Actor(BaseModel):
    """Authenticated actor (user or bot)."""
    actor_id: int
    actor_type: Literal["user", "bot", "group", "channel"]
    role: Literal["OWNER", "EDITOR", "MEMBER", "GUEST"]
    permissions: list[str]


class PermissionCheck(BaseModel):
    """Result of permission check."""
    allowed: bool
    reason: Optional[str] = None
    actor_id: int
    action: str
