"""
TELEGBOT Architecture Layer - Event Types and Models

Defines canonical event structures that all layers must use.
"""

from typing import Optional, Dict, Any, Literal, Set
from pydantic import BaseModel, Field
from datetime import datetime
from enum import Enum


# Resource Type Enum for better performance and type safety
class ResourceType(str, Enum):
    """Enumeration of resource types for audit and permission checks."""
    POST = "post"
    TICKET = "ticket"
    MEMBER = "member"
    BROADCAST = "broadcast"


class CanonicalEvent(BaseModel):
    """
    All incoming Telegram updates normalized to this canonical form.
    
    This is the single source of truth for event structure.
    Every event entering the system must be normalized to this form.
    """
    
    # Event identity
    event_id: str  # Unique identifier
    event_type: Literal["message", "callback_query", "join_request", "poll_answer"]
    platform: Literal["telegram"]
    
    # Actor identity
    user_id: Optional[int] = None
    username: Optional[str] = None
    chat_id: int
    
    # Timing
    timestamp: int  # Unix timestamp
    
    # Event content
    text: Optional[str] = None
    callback_data: Optional[str] = None
    
    # Store only raw_id reference instead of full raw object to save memory
    raw_id: Optional[str] = Field(default=None, description="Reference to raw Telegram object in cache")
    
    class Config:
        frozen = True  # Immutable


class MessageEvent(CanonicalEvent):
    """Message event - user sends text or media."""
    event_type: Literal["message"] = "message"
    message_id: int
    chat_type: Literal["private", "group", "supergroup", "channel"]


class CallbackQueryEvent(CanonicalEvent):
    """Callback event - user clicks inline button."""
    event_type: Literal["callback_query"] = "callback_query"
    callback_query_id: str
    button_label: Optional[str] = None


class JoinRequestEvent(CanonicalEvent):
    """Join request event - user requests to join group."""
    event_type: Literal["join_request"] = "join_request"
    request_id: str
    full_name: Optional[str] = None


class PollAnswerEvent(CanonicalEvent):
    """Poll answer event - user votes in poll."""
    event_type: Literal["poll_answer"] = "poll_answer"
    poll_id: str
    options: tuple[int, ...] = Field(default_factory=tuple, description="Selected option indices (immutable)")
    
    @property
    def option_set(self) -> Set[int]:
        """Get options as a set for O(1) membership testing."""
        return set(self.options)


# Execution intent (generated by Layer 1 - Internal Modules)
class ExecutionIntent(BaseModel):
    """
    Intent generated by Internal Modules.
    
    This is the contract between Layer 1 and Layer 2.
    Layer 1 (Modules) generates intents.
    Layer 2 (Runtime) executes intents.
    """
    
    intent_id: str
    intent_type: Literal[
        "create_draft",
        "preview_post",
        "publish_post",
        "create_ticket",
        "approve_member",
        "broadcast",
    ]
    actor_id: int
    target_type: ResourceType  # Use enum instead of string
    target_id: str
    
    # Intent data
    data: Dict[str, Any]
    
    class Config:
        frozen = True


# Execution plan (generated by Layer 2 - Runtime Services)
class StateMutation(BaseModel):
    """Single state mutation."""
    key: tuple[str, ...] = Field(description="KV key path (immutable)")
    value: Any
    operation: Literal["set", "delete"]


class AuditEntry(BaseModel):
    """Immutable audit log entry."""
    audit_id: str
    timestamp: int
    actor_id: int
    action: str
    resource_type: ResourceType  # Use enum for indexing efficiency
    resource_id: str
    changes: Dict[str, Any]
    success: bool


class OutboxEntry(BaseModel):
    """Staged outbound message."""
    outbox_id: str
    target_chat_id: int
    message_text: str
    buttons: Optional[tuple[Dict[str, str], ...]] = Field(default=None, description="Immutable button list")
    created_at: int


class QueueItem(BaseModel):
    """Delivery work item."""
    queue_item_id: str
    outbox_id: str
    retry_count: int = Field(default=0, ge=0)  # Add validation
    next_retry_at: int


class ExecutionPlan(BaseModel):
    """
    Immutable execution plan produced by Step 5.
    
    This is the contract between the planning phase and commit phase.
    Uses optimized collections for better performance.
    """
    
    plan_id: str
    timestamp: int
    
    # Use tuples for immutable, efficient collections
    state_mutations: tuple[StateMutation, ...] = Field(default_factory=tuple)
    audit_entry: AuditEntry
    aggregate_updates: Dict[str, int]  # KV counter increments
    outbox_entries: tuple[OutboxEntry, ...] = Field(default_factory=tuple)
    queue_items: tuple[QueueItem, ...] = Field(default_factory=tuple)
    
    class Config:
        frozen = True


# FSM State Definition
class FSMState(BaseModel):
    """Finite State Machine state."""
    state_name: str
    timestamp: int
    data: Dict[str, Any]


# Permission/Security Models
class ActorType(str, Enum):
    """Enumeration of actor types."""
    USER = "user"
    BOT = "bot"
    GROUP = "group"
    CHANNEL = "channel"


class ActorRole(str, Enum):
    """Enumeration of actor roles."""
    OWNER = "OWNER"
    EDITOR = "EDITOR"
    MEMBER = "MEMBER"
    GUEST = "GUEST"


class Actor(BaseModel):
    """Authenticated actor (user or bot)."""
    actor_id: int
    actor_type: ActorType  # Use enum for efficiency
    role: ActorRole  # Use enum for efficiency
    permissions: frozenset[str] = Field(
        default_factory=frozenset,
        description="Immutable permission set for O(1) lookup"
    )
    
    @classmethod
    def model_validate(cls, obj):
        """Override to convert lists to frozensets."""
        if isinstance(obj, dict) and "permissions" in obj:
            if isinstance(obj["permissions"], list):
                obj = {**obj, "permissions": frozenset(obj["permissions"])}
        return super().model_validate(obj)


class PermissionCheck(BaseModel):
    """Result of permission check."""
    allowed: bool
    reason: Optional[str] = Field(default=None)
    actor_id: int
    action: str
